/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import entity.Customer;

/**
 *
 * @author dalmir
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        projectDescriptionLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        rightSidePanel = new javax.swing.JPanel();
        incomingCallHeaderPanel = new javax.swing.JPanel();
        incomingCallLabel = new javax.swing.JLabel();
        incomingCallMainPanel = new javax.swing.JPanel();
        incomingCallScrollPane = new javax.swing.JScrollPane();
        incomingCallList = new javax.swing.JList();
        bodyPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchDropDown = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        searchMessageLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        cpfLabelFixed = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        residentialPhoneLavelFixed = new javax.swing.JLabel();
        residentialPhoneLabel = new javax.swing.JLabel();
        faxLabelFixed = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        cellPhoneLabelFixed = new javax.swing.JLabel();
        cellPhoneLabel = new javax.swing.JLabel();
        emailLabelFixed = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        corporateNameLabelFixed = new javax.swing.JLabel();
        corporateNameLabel = new javax.swing.JLabel();
        cityLabelFixed = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        districtLabelFixed = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        addressLabelFixed = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        businessPhoneLabelFixed = new javax.swing.JLabel();
        businessPhoneLabel = new javax.swing.JLabel();
        birthDateLabelFixed = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        legalPersonLavelFixed = new javax.swing.JLabel();
        legalPersonLabel = new javax.swing.JLabel();
        recordLabelFixed = new javax.swing.JLabel();
        recordLabel = new javax.swing.JLabel();
        postLabelFixed = new javax.swing.JLabel();
        postLabel = new javax.swing.JLabel();
        problemsLabelFixed = new javax.swing.JLabel();
        problemsLabel = new javax.swing.JLabel();
        observationLabelFixed = new javax.swing.JLabel();
        observationScrollPannel = new javax.swing.JScrollPane();
        observationTextPane = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(201, 208, 209));
        headerPanel.setPreferredSize(new java.awt.Dimension(762, 60));

        projectLabel.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        projectLabel.setText("IDentiCALL");

        projectDescriptionLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        projectDescriptionLabel.setText("Identificação de Chamadas");

        versionLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        versionLabel.setText("BETA");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addComponent(projectDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionLabel))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        rightSidePanel.setPreferredSize(new java.awt.Dimension(260, 445));
        rightSidePanel.setLayout(new java.awt.BorderLayout());

        incomingCallHeaderPanel.setBackground(new java.awt.Color(232, 232, 232));
        incomingCallHeaderPanel.setPreferredSize(new java.awt.Dimension(250, 35));

        incomingCallLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        incomingCallLabel.setText("Ligações recentes");

        javax.swing.GroupLayout incomingCallHeaderPanelLayout = new javax.swing.GroupLayout(incomingCallHeaderPanel);
        incomingCallHeaderPanel.setLayout(incomingCallHeaderPanelLayout);
        incomingCallHeaderPanelLayout.setHorizontalGroup(
            incomingCallHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomingCallHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomingCallLabel)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        incomingCallHeaderPanelLayout.setVerticalGroup(
            incomingCallHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        rightSidePanel.add(incomingCallHeaderPanel, java.awt.BorderLayout.PAGE_START);

        incomingCallList.setBackground(new java.awt.Color(178, 171, 171));
        incomingCallList.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        incomingCallList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "(00) 0000 0000 00:00 00/00/0000", "(00) 0000 0000 00:00 00/00/0000", "(00) 0000 0000 00:00 00/00/0000", "(00) 0000 0000 00:00 00/00/0000", "(00) 0000 0000 00:00 00/00/0000" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        incomingCallList.setToolTipText("");
        incomingCallList.setSelectionBackground(new java.awt.Color(80, 80, 80));
        incomingCallList.setSelectionForeground(new java.awt.Color(254, 254, 254));
        incomingCallScrollPane.setViewportView(incomingCallList);

        javax.swing.GroupLayout incomingCallMainPanelLayout = new javax.swing.GroupLayout(incomingCallMainPanel);
        incomingCallMainPanel.setLayout(incomingCallMainPanelLayout);
        incomingCallMainPanelLayout.setHorizontalGroup(
            incomingCallMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        incomingCallMainPanelLayout.setVerticalGroup(
            incomingCallMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        rightSidePanel.add(incomingCallMainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(rightSidePanel, java.awt.BorderLayout.LINE_END);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(195, 217, 255));
        searchPanel.setPreferredSize(new java.awt.Dimension(638, 35));

        searchLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        searchLabel.setText("Pesquisar:");

        searchTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 168, 168)));
        searchTextField.setPreferredSize(new java.awt.Dimension(2, 27));
        searchTextField.setRequestFocusEnabled(false);

        searchDropDown.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "CPF", "Telefone" }));
        searchDropDown.setBorder(null);
        searchDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDropDownActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchButton.setText("Pesquisar");
        searchButton.setPreferredSize(new java.awt.Dimension(78, 28));

        searchMessageLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchMessageLabel.setText("...");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchMessageLabel)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchMessageLabel))
        );

        bodyPanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        formPanel.setBackground(new java.awt.Color(254, 254, 254));

        nameLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        nameLabel.setText("<Nome do cliente>");

        cpfLabelFixed.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cpfLabelFixed.setText("CPF/CNPJ:");

        cpfLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cpfLabel.setText("--------- --");

        residentialPhoneLavelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        residentialPhoneLavelFixed.setText("Fone Residencial:");

        residentialPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        residentialPhoneLabel.setText("(--) ---- ----");

        faxLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        faxLabelFixed.setText("Fax:");

        faxLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        faxLabel.setText("(--) ---- ----");

        cellPhoneLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        cellPhoneLabelFixed.setText("Celular:");

        cellPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        cellPhoneLabel.setText("(--) ---- ----");

        emailLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        emailLabelFixed.setText("Email:");

        emailLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        emailLabel.setText("---");

        corporateNameLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        corporateNameLabelFixed.setText("Razão Social:");

        corporateNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        corporateNameLabel.setText("---");

        cityLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        cityLabelFixed.setText("Cidade:");

        cityLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        cityLabel.setText("---");

        districtLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        districtLabelFixed.setText("Bairro:");

        districtLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        districtLabel.setText("---");

        addressLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        addressLabelFixed.setText("Endereço:");

        addressLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        addressLabel.setText("---");

        businessPhoneLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        businessPhoneLabelFixed.setText("Fone Comecial:");

        businessPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        businessPhoneLabel.setText("(--) ---- ----");

        birthDateLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        birthDateLabelFixed.setText("Nascimento:");

        birthDateLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        birthDateLabel.setText("--/--/----");

        legalPersonLavelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        legalPersonLavelFixed.setText("Pessoa:");

        legalPersonLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        legalPersonLabel.setText("---");

        recordLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        recordLabelFixed.setText("Data Cadastro:");

        recordLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        recordLabel.setText("--/--/----");

        postLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        postLabelFixed.setText("Correio:");

        postLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        postLabel.setText("---");

        problemsLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        problemsLabelFixed.setText("Problemas:");

        problemsLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        problemsLabel.setText("---");

        observationLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        observationLabelFixed.setText("Observação:");

        observationTextPane.setEditable(false);
        observationTextPane.setBorder(null);
        observationTextPane.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        observationScrollPannel.setViewportView(observationTextPane);

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(observationScrollPannel))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observationLabelFixed)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(businessPhoneLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(businessPhoneLabel))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(districtLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(districtLabel))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(corporateNameLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corporateNameLabel))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residentialPhoneLavelFixed)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(postLabelFixed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(postLabel)))
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(residentialPhoneLabel))
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(problemsLabelFixed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(problemsLabel))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(recordLabelFixed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(recordLabel))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(legalPersonLavelFixed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(legalPersonLabel))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(cityLabelFixed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cityLabel))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(addressLabelFixed)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addressLabel))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(faxLabelFixed)
                                                    .addComponent(emailLabelFixed))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailLabel)
                                                    .addComponent(faxLabel)))))))
                            .addComponent(nameLabel)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(cellPhoneLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cellPhoneLabel))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(cpfLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfLabel))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(birthDateLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthDateLabel)))
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addGap(12, 12, 12)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabelFixed)
                    .addComponent(cpfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residentialPhoneLavelFixed)
                    .addComponent(residentialPhoneLabel)
                    .addComponent(faxLabelFixed)
                    .addComponent(faxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellPhoneLabelFixed)
                    .addComponent(cellPhoneLabel)
                    .addComponent(emailLabelFixed)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corporateNameLabelFixed)
                    .addComponent(corporateNameLabel)
                    .addComponent(addressLabelFixed)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtLabelFixed)
                    .addComponent(districtLabel)
                    .addComponent(cityLabelFixed)
                    .addComponent(cityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessPhoneLabelFixed)
                    .addComponent(businessPhoneLabel)
                    .addComponent(legalPersonLavelFixed)
                    .addComponent(legalPersonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateLabelFixed)
                    .addComponent(birthDateLabel)
                    .addComponent(recordLabelFixed)
                    .addComponent(recordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(problemsLabelFixed)
                    .addComponent(problemsLabel)
                    .addComponent(postLabelFixed)
                    .addComponent(postLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(observationLabelFixed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observationScrollPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        bodyPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Arquivo");
        menuBar.add(jMenu1);

        jMenu2.setText("Editar");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabelFixed;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JLabel birthDateLabelFixed;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel businessPhoneLabel;
    private javax.swing.JLabel businessPhoneLabelFixed;
    private javax.swing.JLabel cellPhoneLabel;
    private javax.swing.JLabel cellPhoneLabelFixed;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabelFixed;
    private javax.swing.JLabel corporateNameLabel;
    private javax.swing.JLabel corporateNameLabelFixed;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel cpfLabelFixed;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JLabel districtLabelFixed;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabelFixed;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JLabel faxLabelFixed;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel incomingCallHeaderPanel;
    private javax.swing.JLabel incomingCallLabel;
    private javax.swing.JList incomingCallList;
    private javax.swing.JPanel incomingCallMainPanel;
    private javax.swing.JScrollPane incomingCallScrollPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel legalPersonLabel;
    private javax.swing.JLabel legalPersonLavelFixed;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel observationLabelFixed;
    private javax.swing.JScrollPane observationScrollPannel;
    private javax.swing.JTextPane observationTextPane;
    private javax.swing.JLabel postLabel;
    private javax.swing.JLabel postLabelFixed;
    private javax.swing.JLabel problemsLabel;
    private javax.swing.JLabel problemsLabelFixed;
    private javax.swing.JLabel projectDescriptionLabel;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel recordLabel;
    private javax.swing.JLabel recordLabelFixed;
    private javax.swing.JLabel residentialPhoneLabel;
    private javax.swing.JLabel residentialPhoneLavelFixed;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchDropDown;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel searchMessageLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

    public void setForm(Customer customer) {
        nameLabel.setText(customer.getName());
        cpfLabel.setText(customer.getCpf());
        residentialPhoneLabel.setText(customer.getResidentialPhone());
        faxLabel.setText(customer.getFax());
        cellPhoneLabel.setText(customer.getCellPhone());
        emailLabel.setText(customer.getEmail());
        legalPersonLabel.setText(customer.getLegalPerson());
        addressLabel.setText(customer.getAddress());
        districtLabel.setText(customer.getDistrict());
        cityLabel.setText(customer.getCity());
        businessPhoneLabel.setText(customer.getBusinessPhone());
        legalPersonLabel.setText(customer.getLegalPerson());
        birthDateLabel.setText(customer.getBirthDate());
        recordLabel.setText(customer.getRecortDate());
        postLabel.setText(customer.getPost() ? "Sim" : "Não");
        problemsLabel.setText(customer.getProblems() ? "Sim" : "Não");
        observationTextPane.setText(customer.getObservation());
    }
}
