/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import entity.Customer;
import identicall.CustomerSearchListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author dalmir
 */
public class MainWindow extends javax.swing.JFrame {

    static {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    private CustomerSearchListener searchListener;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(CustomerSearchListener searchListener) {
        initComponents();
        this.searchListener = searchListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        projectDescriptionLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        rightSidePanel = new javax.swing.JPanel();
        incomingCallHeaderPanel = new javax.swing.JPanel();
        incomingCallLabel = new javax.swing.JLabel();
        incomingCallMainPanel = new javax.swing.JPanel();
        incomingCallScrollPane = new javax.swing.JScrollPane();
        incomingCallList = new javax.swing.JList();
        bodyPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchMessageLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchComboBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        cpfCnpjLabelFixed = new javax.swing.JLabel();
        cpfCnpjLabel = new javax.swing.JLabel();
        residentialPhoneLavelFixed = new javax.swing.JLabel();
        residentialPhoneLabel = new javax.swing.JLabel();
        faxLabelFixed = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        cellPhoneLabelFixed = new javax.swing.JLabel();
        cellPhoneLabel = new javax.swing.JLabel();
        emailLabelFixed = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        corporateNameLabelFixed = new javax.swing.JLabel();
        corporateNameLabel = new javax.swing.JLabel();
        cityLabelFixed = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        districtLabelFixed = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        addressLabelFixed = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        businessPhoneLabelFixed = new javax.swing.JLabel();
        businessPhoneLabel = new javax.swing.JLabel();
        birthDateLabelFixed = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        legalPersonLavelFixed = new javax.swing.JLabel();
        legalPersonLabel = new javax.swing.JLabel();
        recordLabelFixed = new javax.swing.JLabel();
        recordLabel = new javax.swing.JLabel();
        postLabelFixed = new javax.swing.JLabel();
        postLabel = new javax.swing.JLabel();
        problemsLabelFixed = new javax.swing.JLabel();
        problemsLabel = new javax.swing.JLabel();
        observationLabelFixed = new javax.swing.JLabel();
        observationScrollPannel = new javax.swing.JScrollPane();
        observationTextPane = new javax.swing.JTextPane();
        stateAbbreviationLabelFixed = new javax.swing.JLabel();
        stateAbbreviationLabel = new javax.swing.JLabel();
        municipalityLabelFixed = new javax.swing.JLabel();
        municipalityLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(201, 208, 209));
        headerPanel.setPreferredSize(new java.awt.Dimension(762, 60));

        projectLabel.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        projectLabel.setText("IDentiCALL");

        projectDescriptionLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        projectDescriptionLabel.setText("Identificação de Chamadas");

        versionLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        versionLabel.setText("BETA");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addComponent(projectDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionLabel))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        rightSidePanel.setMaximumSize(new java.awt.Dimension(270, 445));
        rightSidePanel.setPreferredSize(new java.awt.Dimension(270, 445));
        rightSidePanel.setLayout(new java.awt.BorderLayout());

        incomingCallHeaderPanel.setBackground(new java.awt.Color(232, 232, 232));
        incomingCallHeaderPanel.setPreferredSize(new java.awt.Dimension(250, 36));

        incomingCallLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        incomingCallLabel.setText("Ligações recentes");

        javax.swing.GroupLayout incomingCallHeaderPanelLayout = new javax.swing.GroupLayout(incomingCallHeaderPanel);
        incomingCallHeaderPanel.setLayout(incomingCallHeaderPanelLayout);
        incomingCallHeaderPanelLayout.setHorizontalGroup(
            incomingCallHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomingCallHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomingCallLabel)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        incomingCallHeaderPanelLayout.setVerticalGroup(
            incomingCallHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        rightSidePanel.add(incomingCallHeaderPanel, java.awt.BorderLayout.PAGE_START);

        incomingCallMainPanel.setPreferredSize(new java.awt.Dimension(300, 485));

        incomingCallList.setBackground(new java.awt.Color(178, 171, 171));
        incomingCallList.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        incomingCallList.setToolTipText("");
        incomingCallList.setPreferredSize(new java.awt.Dimension(200, 26));
        incomingCallList.setSelectionBackground(new java.awt.Color(80, 80, 80));
        incomingCallList.setSelectionForeground(new java.awt.Color(254, 254, 254));
        incomingCallList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incomingCallListMouseClicked(evt);
            }
        });
        incomingCallList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                incomingCallListValueChanged(evt);
            }
        });
        incomingCallScrollPane.setViewportView(incomingCallList);

        javax.swing.GroupLayout incomingCallMainPanelLayout = new javax.swing.GroupLayout(incomingCallMainPanel);
        incomingCallMainPanel.setLayout(incomingCallMainPanelLayout);
        incomingCallMainPanelLayout.setHorizontalGroup(
            incomingCallMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        incomingCallMainPanelLayout.setVerticalGroup(
            incomingCallMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomingCallScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        rightSidePanel.add(incomingCallMainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(rightSidePanel, java.awt.BorderLayout.LINE_END);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(195, 217, 255));
        searchPanel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchPanel.setPreferredSize(new java.awt.Dimension(638, 35));

        searchLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchLabel.setText("Pesquisar:");

        searchMessageLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchMessageLabel.setText("   ");

        searchTextField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchTextField.setPreferredSize(new java.awt.Dimension(73, 25));

        searchComboBox.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telefone", "CPF/CNPF", "Nome" }));
        searchComboBox.setPreferredSize(new java.awt.Dimension(73, 25));

        searchButton.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchButton.setText("Pesquisar");
        searchButton.setPreferredSize(new java.awt.Dimension(73, 27));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bodyPanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        formPanel.setBackground(new java.awt.Color(254, 254, 254));

        nameLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        nameLabel.setText("<Cliente não econtrado>");

        cpfCnpjLabelFixed.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cpfCnpjLabelFixed.setText("CPF/CNPJ:");

        cpfCnpjLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cpfCnpjLabel.setText("--------- --");

        residentialPhoneLavelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        residentialPhoneLavelFixed.setText("Fone Residencial:");

        residentialPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        residentialPhoneLabel.setText("(--) --------");

        faxLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        faxLabelFixed.setText("Fax:");

        faxLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        faxLabel.setText("(--) --------");

        cellPhoneLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        cellPhoneLabelFixed.setText("Celular:");

        cellPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        cellPhoneLabel.setText("(--) --------");

        emailLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        emailLabelFixed.setText("Email:");

        emailLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        emailLabel.setText("---");

        corporateNameLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        corporateNameLabelFixed.setText("Razão Social:");

        corporateNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        corporateNameLabel.setText("---");

        cityLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        cityLabelFixed.setText("Cidade:");

        cityLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        cityLabel.setText("---");

        districtLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        districtLabelFixed.setText("Bairro:");

        districtLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        districtLabel.setText("---");

        addressLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        addressLabelFixed.setText("Endereço:");

        addressLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        addressLabel.setText("---");

        businessPhoneLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        businessPhoneLabelFixed.setText("Fone Comecial:");

        businessPhoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        businessPhoneLabel.setText("(--) --------");

        birthDateLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        birthDateLabelFixed.setText("Nascimento:");

        birthDateLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        birthDateLabel.setText("--/--/----");

        legalPersonLavelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        legalPersonLavelFixed.setText("Pessoa:");

        legalPersonLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        legalPersonLabel.setText("---");

        recordLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        recordLabelFixed.setText("Data Cadastro:");

        recordLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        recordLabel.setText("--/--/----");

        postLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        postLabelFixed.setText("Correio:");

        postLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        postLabel.setText("---");

        problemsLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        problemsLabelFixed.setText("Problemas:");

        problemsLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        problemsLabel.setText("---");

        observationLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        observationLabelFixed.setText("Observação:");

        observationTextPane.setEditable(false);
        observationTextPane.setBorder(null);
        observationTextPane.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        observationTextPane.setText("---");
        observationScrollPannel.setViewportView(observationTextPane);

        stateAbbreviationLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        stateAbbreviationLabelFixed.setText("Estado:");

        stateAbbreviationLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        stateAbbreviationLabel.setText("--");

        municipalityLabelFixed.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        municipalityLabelFixed.setText("Município:");

        municipalityLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        municipalityLabel.setText("---");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observationScrollPannel)
                    .addComponent(observationLabelFixed)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(cpfCnpjLabelFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfCnpjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(birthDateLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(postLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(stateAbbreviationLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateAbbreviationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(legalPersonLavelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(legalPersonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(districtLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(districtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(cellPhoneLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cellPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(residentialPhoneLavelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentialPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(businessPhoneLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(businessPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(faxLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(faxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(addressLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(emailLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(cityLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(municipalityLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipalityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(corporateNameLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corporateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(recordLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(problemsLabelFixed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(problemsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCnpjLabelFixed)
                    .addComponent(cpfCnpjLabel))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faxLabelFixed)
                    .addComponent(faxLabel)
                    .addComponent(cellPhoneLabelFixed)
                    .addComponent(cellPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelFixed)
                    .addComponent(emailLabel)
                    .addComponent(residentialPhoneLavelFixed)
                    .addComponent(residentialPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabelFixed)
                    .addComponent(addressLabel)
                    .addComponent(businessPhoneLabelFixed)
                    .addComponent(businessPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtLabelFixed)
                    .addComponent(districtLabel)
                    .addComponent(cityLabelFixed)
                    .addComponent(cityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipalityLabelFixed)
                    .addComponent(municipalityLabel)
                    .addComponent(stateAbbreviationLabelFixed)
                    .addComponent(stateAbbreviationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corporateNameLabelFixed)
                    .addComponent(corporateNameLabel)
                    .addComponent(postLabelFixed)
                    .addComponent(postLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateLabelFixed)
                    .addComponent(birthDateLabel)
                    .addComponent(recordLabelFixed)
                    .addComponent(recordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legalPersonLavelFixed)
                    .addComponent(legalPersonLabel)
                    .addComponent(problemsLabelFixed)
                    .addComponent(problemsLabel))
                .addGap(18, 18, 18)
                .addComponent(observationLabelFixed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observationScrollPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        bodyPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("Arquivo");
        fileMenu.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        menuBar.add(fileMenu);

        helpMenu.setText("Ajuda");
        helpMenu.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String searchText = searchTextField.getText();
        if (searchText.length() < 3) {
            searchMessageLabel.setText("Preencha o campo.");
            return;
        }
        searchText = "%" + searchText + "%";
        int selectedIndex = searchComboBox.getSelectedIndex();
        List<Customer> examples = new ArrayList<>();
        switch (selectedIndex) {
            case 0:
                Customer cellPhoneExample = new Customer();
                cellPhoneExample.setCellPhone(searchText);
                Customer businessPhoneExample = new Customer();
                businessPhoneExample.setBusinessPhone(searchText);
                Customer residentialBusinessPhone = new Customer();
                residentialBusinessPhone.setResidentialPhone(searchText);
                examples.add(cellPhoneExample);
                examples.add(businessPhoneExample);
                examples.add(residentialBusinessPhone);
                break;
            case 1:
                Customer cpfExample = new Customer();
                cpfExample.setCpfCnpj(searchText);
                examples.add(cpfExample);
                break;
            case 2:
                Customer nameExample = new Customer();
                nameExample.setName(searchText);
                examples.add(nameExample);
                break;
        }
        int found = searchListener.onCustomerSearch(examples, searchTextField.getText(), false);
        if (found > 0) {
            searchMessageLabel.setText(" ");
        } else {
            searchMessageLabel.setText("Nenhum cliente encontrado.");
            emptyCustomer();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void incomingCallListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_incomingCallListValueChanged
    }//GEN-LAST:event_incomingCallListValueChanged

    private void incomingCallListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomingCallListMouseClicked
        String selected = (String) incomingCallList.getSelectedValue();
        StringBuilder number = new StringBuilder();
        number.append(selected.substring(1, 3));
        number.append(selected.substring(5, 13));
        String numberString = number.toString();
        List<Customer> examples = new ArrayList<>();
        Customer cellPhoneExample = new Customer();
        cellPhoneExample.setCellPhone(numberString);
        Customer businessPhoneExample = new Customer();
        businessPhoneExample.setBusinessPhone(numberString);
        Customer residentialBusinessPhone = new Customer();
        residentialBusinessPhone.setResidentialPhone(numberString);
        examples.add(cellPhoneExample);
        examples.add(businessPhoneExample);
        examples.add(residentialBusinessPhone);
        searchListener.onCustomerSearch(examples, number.toString(), false);
    }//GEN-LAST:event_incomingCallListMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabelFixed;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JLabel birthDateLabelFixed;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel businessPhoneLabel;
    private javax.swing.JLabel businessPhoneLabelFixed;
    private javax.swing.JLabel cellPhoneLabel;
    private javax.swing.JLabel cellPhoneLabelFixed;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabelFixed;
    private javax.swing.JLabel corporateNameLabel;
    private javax.swing.JLabel corporateNameLabelFixed;
    private javax.swing.JLabel cpfCnpjLabel;
    private javax.swing.JLabel cpfCnpjLabelFixed;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JLabel districtLabelFixed;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabelFixed;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JLabel faxLabelFixed;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel incomingCallHeaderPanel;
    private javax.swing.JLabel incomingCallLabel;
    private javax.swing.JList incomingCallList;
    private javax.swing.JPanel incomingCallMainPanel;
    private javax.swing.JScrollPane incomingCallScrollPane;
    private javax.swing.JLabel legalPersonLabel;
    private javax.swing.JLabel legalPersonLavelFixed;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel municipalityLabel;
    private javax.swing.JLabel municipalityLabelFixed;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel observationLabelFixed;
    private javax.swing.JScrollPane observationScrollPannel;
    private javax.swing.JTextPane observationTextPane;
    private javax.swing.JLabel postLabel;
    private javax.swing.JLabel postLabelFixed;
    private javax.swing.JLabel problemsLabel;
    private javax.swing.JLabel problemsLabelFixed;
    private javax.swing.JLabel projectDescriptionLabel;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel recordLabel;
    private javax.swing.JLabel recordLabelFixed;
    private javax.swing.JLabel residentialPhoneLabel;
    private javax.swing.JLabel residentialPhoneLavelFixed;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchComboBox;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel searchMessageLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel stateAbbreviationLabel;
    private javax.swing.JLabel stateAbbreviationLabelFixed;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

    public void populateCustomer(Customer customer) {
        nameLabel.setText(customer.getName());
        cpfCnpjLabel.setText(customer.getCpfCnpj());
        residentialPhoneLabel.setText(customer.getResidentialPhone());
        faxLabel.setText(customer.getFax());
        cellPhoneLabel.setText(customer.getCellPhone());
        emailLabel.setText(customer.getEmail());
        legalPersonLabel.setText(customer.getLegalPerson());
        addressLabel.setText(customer.getAddress());
        districtLabel.setText(customer.getDistrict());
        cityLabel.setText(customer.getCity());
        stateAbbreviationLabel.setText(customer.getStateAbbreviation());
        districtLabel.setText(customer.getDistrict());
        municipalityLabel.setText(customer.getMunicipality());
        businessPhoneLabel.setText(customer.getBusinessPhone());
        legalPersonLabel.setText(customer.getLegalPerson());
        corporateNameLabel.setText(customer.getCorporateName());
        birthDateLabel.setText(customer.getBirthDate());
        recordLabel.setText(customer.getRecortDate());
        postLabel.setText(customer.getPost() ? "Sim" : "Não");
        problemsLabel.setText(customer.getProblems() ? "Sim" : "Não");
        observationTextPane.setText(customer.getObservation());
    }

    public void emptyCustomer() {
        Customer customer = new Customer();
        customer.setName("<Cliente não encontrado>");
        customer.setAddress("---");
        customer.setBirthDate("--/--/----");
        customer.setBusinessPhone("(--) --------");
        customer.setCellPhone("(--) --------");
        customer.setCity("---");
        customer.setCorporateName("---");
        customer.setCpfCnpj("---");
        customer.setDistrict("---");
        customer.setEmail("---");
        customer.setFax("(--) --------");
        customer.setLegalPerson("---");
        customer.setMunicipality("---");
        customer.setObservation("");
        customer.setPost(false);
        customer.setProblems(false);
        customer.setRecortDate("--/--/----");
        customer.setResidentialPhone("(--) --------");
        customer.setStateAbbreviation("---");
        populateCustomer(customer);
    }

    public void appendRecentCall(String recentCall) {
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement(recentCall);
        for (int i = 0; i < incomingCallList.getModel().getSize(); i++) {
            listModel.addElement(incomingCallList.getModel().getElementAt(i));
        }
        incomingCallList.setModel(listModel);
    }
}
